---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ethereum2-3500-prysm
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "eth2-3500-prysm.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - ethereum2-3500-prysm
  http:
  - route:
    - destination:
        host: ethereum2-prysm
        port:
          number: 3500
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ethereum2-3500-prysm
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "eth2-3500-prysm.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ethereum2-4000-prysm
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "eth2-4000-prysm.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - ethereum2-4000-prysm
  http:
  - route:
    - destination:
        host: ethereum2-grpc-prysm
        port:
          number: 4000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ethereum2-4000-prysm
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: GRPC
    hosts:
    - "eth2-4000-prysm.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum2-grpc-prysm
  namespace: REPLACE_NAMESPACE
  labels:
    application: ethereum2-prysm
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
      name: grpc
  selector:
    application: ethereum2-prysm
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum2-prysm
  namespace: REPLACE_NAMESPACE
  labels:
    application: ethereum2-prysm
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 3500
      protocol: TCP
      targetPort: 3500
      name: ext-3500
    - port: 4000
      protocol: TCP
      targetPort: 4000
      name: ext-4000
    - port: 6668
      protocol: TCP
      targetPort: 6668
      name: ext-6668
    - port: 13000
      protocol: TCP
      targetPort: 13000
      name: ext-13000
  selector:
    application: ethereum2-prysm
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: REPLACE_API_VERSION
kind: StatefulSet
metadata:
  namespace: REPLACE_NAMESPACE
  name: ethereum2-prysm
spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: ethereum2-prysm
      application: ethereum2-prysm
  serviceName: ethereum2-prysm
  template:
    metadata:
      labels:
        name: ethereum2-prysm
        application: ethereum2-prysm
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  application: ethereum2-prysm
              topologyKey: kubernetes.io/hostname
            weight: 1
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - blockchain
      containers:
      - name: ethereum2-prysm
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        ports:
        - containerPort: 3500
          name: ext-3500
        - containerPort: 4000
          name: ext-4000
        - containerPort: 6668
          name: ext-6668
        - containerPort: 13000
          name: ext-13000
        volumeMounts:
        - mountPath: "/data"
          name: ethereum2-prysm
      - name: ubuntu
        image: 121827225315.dkr.ecr.us-west-2.amazonaws.com/infra-stage-repo:ubuntu20
        imagePullPolicy: Always
        args: [bash, -c, sleep infinity]
        volumeMounts:
        - name: ethereum2-script-prysm
          mountPath: /root/sync-status.sh
          subPath: sync-status.sh
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /root/sync-status.sh
          initialDelaySeconds: 10
          periodSeconds: 15
      volumes:
      - persistentVolumeClaim:
          claimName: ethereum2-prysm
        name: ethereum2-prysm
      - name: ethereum2-script-prysm
        configMap:
          name: ethereum2-script-prysm
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/role
        operator: Exists 
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: ethereum2-prysm
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: gp2
